apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-test-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/akox45/cicd2
    targetRevision: HEAD
    path: app/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-test-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 